import { useEffect,useRef,useState } from 'react';
import { ArrowLeft,Flame,Flag } from 'lucide-react';
import { database,ref,runTransaction } from '../utils/firebase';
import { FLEET,shipCells,randomFleet,square,updateBattleship } from '../utils/battleship';
const button='rounded-xl border border-white/15 px-4 py-2 text-sm hover:bg-white/5 disabled:opacity-40';
const coordinate=(r,c)=>`${String.fromCharCode(65+c)}${r+1}`;
function Board({fleet={},shots={},interactive=false,onCell,label,selected}){
  const occupied=new Set();
  for(const ship of FLEET){const p=fleet[ship.id];if(p)shipCells(p.row,p.col,ship.size,p.vertical).forEach(cell=>occupied.add(cell));}
  return <div className={`battle-board ${label==='Your fleet'?'battle-board-own':''}`}><h3 className="text-lg font-medium text-white">{label}</h3><p className="mt-1 mb-4 text-[10px] uppercase tracking-widest text-white/40">{label==='Your fleet'?'5 ships · 17 tiles':interactive?'Take the shot':'Uncharted territory'}</p><div className="ml-5 grid grid-cols-10 pb-2 text-center text-[10px] text-white/65">{Array.from({length:10},(_,i)=><span key={i}>{String.fromCharCode(65+i)}</span>)}</div><div className="flex"><div className="grid w-5 shrink-0 items-center text-[10px] text-white/60" style={{gridTemplateRows: 'repeat(10, minmax(0, 1fr))'}}>{Array.from({length:10},(_,i)=><span key={i}>{i+1}</span>)}</div><div className="battle-ocean relative min-w-0 flex-1"><div className="grid grid-cols-10" aria-label={label}>{Array.from({length:100},(_,i)=>{
    const r=Math.floor(i/10),c=i%10,key=square(r,c),shot=shots[key],ship=occupied.has(key);
    return <button type="button" key={key} aria-label={`${label} ${coordinate(r,c)}${shot?shot.hit?' hit':' miss':ship?' ship':''}`} disabled={!interactive||!!shot} onClick={()=>onCell(r,c)} className={`battle-cell ${selected===key?'battle-target':''} ${interactive&&!shot?'battle-cell-active':''}`}>{shot?<span className={shot.hit?'battle-hit':'battle-miss'}>{shot.hit?'✹':'●'}</span>:ship?<span className="battle-ship-dot">·</span>:''}</button>;
  })}</div><div aria-hidden="true" className="pointer-events-none absolute inset-0">{FLEET.map(ship=>{const p=fleet[ship.id];return p?<div key={ship.id} className="battle-ship" style={{left:`${p.col*10+.7}%`,top:`${p.row*10+.7}%`,width:`${(p.vertical?1:ship.size)*10-1.4}%`,height:`${(p.vertical?ship.size:1)*10-1.4}%`}}/>:null;})}</div></div></div><div className="mt-3 flex gap-4 text-[10px] text-white/40"><span className="text-orange-300">✹ Hit</span><span className="text-purple-300">● Miss</span></div></div>;
}
export default function Battleship({roomCode,currentUser,game,featured=false,onOpen,onClose}){
  const [fleet,setFleet]=useState({}),[selectedShip,setSelectedShip]=useState('carrier'),[vertical,setVertical]=useState(false),[target,setTarget]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirmFinish,setConfirmFinish]=useState(false);
  const lock=useRef(false),player=game?.players?.[currentUser?.id],opponent=Object.values(game?.players||{}).find(p=>p.id!==currentUser?.id),finished=game?.status==='finished',myTurn=game?.status==='playing'&&game.turn===currentUser?.id;
  useEffect(()=>{setFleet(game?.fleets?.[currentUser?.id]||{});setTarget(null);setError('');setConfirmFinish(false);},[game?.id,currentUser?.id]);
  useEffect(()=>setTarget(null),[game?.revision]);
  async function act(type,extra={}){
    if(lock.current)return;lock.current=true;setBusy(true);setError('');
    try{const action={type,id:crypto.randomUUID(),user:currentUser,now:Date.now(),expectedGameId:game?.id||null,expectedRevision:game?.revision,...extra};
      const result=await runTransaction(ref(database,`karaoke-rooms/${roomCode}/battleshipGame`),existing=>updateBattleship(existing,action),{applyLocally:false});
      if(!result.committed)throw new Error('Could not save. Try again.');if(type==='start'||type==='join')onOpen?.();setConfirmFinish(false);
    }catch(cause){setError(cause.message||'Could not save your move.');}finally{lock.current=false;setBusy(false);}
  }
  function place(r,c){
    try{const ship=FLEET.find(s=>s.id===selectedShip),cells=shipCells(r,c,ship.size,vertical),used=new Set();
      for(const other of FLEET){const p=fleet[other.id];if(p&&other.id!==ship.id)shipCells(p.row,p.col,other.size,p.vertical).forEach(key=>used.add(key));}
      if(cells.some(key=>used.has(key)))throw new Error('Ships cannot overlap.');
      setFleet({...fleet,[ship.id]:{row:r,col:c,vertical}});setError('');const next=FLEET.find(s=>s.id!==ship.id&&!fleet[s.id]);if(next)setSelectedShip(next.id);
    }catch(cause){setError(cause.message);}
  }
  const status=finished?game.winnerId?`${game.winnerName} wins!`:'Game finished':!game?'Hide your fleet. Find theirs.':!player?'Your person left a battle for you':game.status==='setup'?player.ready?'Your ships are ready. Waiting for your person.':'Place your five ships':myTurn?'Your turn · Choose a square to fire':`${game.players[game.turn]?.name||'Your person'}’s turn · Come back later`;
  const battleLog=Object.entries(game?.shots||{}).flatMap(([userId,shots])=>Object.entries(shots).map(([cell,shot])=>({...shot,cell,userId,name:game.players?.[userId]?.name||'Someone'}))).sort((a,b)=>b.at-a.at);
  const content=<>{!featured&&<p className="text-sm text-white/60">{status}</p>}{error&&<p role="alert" className="text-sm text-violet-300">{error}</p>}
    {!game||finished?<button className={button} disabled={busy} onClick={()=>act('start')}>{finished?'Play again':'Start game'}</button>:!player?<button className={button} disabled={busy} onClick={()=>act('join')}>Join game</button>:!featured?<button className={button} onClick={onOpen}>Open game</button>:null}
    {featured&&player&&!finished&&<>
      {game.status==='setup'&&!player.ready?<div className="space-y-4"><div className="flex flex-wrap gap-2">{FLEET.map(ship=><button key={ship.id} className={`${button} ${selectedShip===ship.id?'border-violet-300 text-violet-300':''}`} onClick={()=>setSelectedShip(ship.id)} disabled={busy}>{ship.name} ({ship.size}) {fleet[ship.id]?'✓':''}</button>)}</div><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>setVertical(!vertical)} disabled={busy}>Rotate · {vertical?'Vertical':'Horizontal'}</button><button className={button} onClick={()=>{setFleet(randomFleet());setError('');}} disabled={busy}>Random placement</button><button className={button} onClick={()=>setFleet({})} disabled={busy}>Clear ships</button></div><p className="text-sm text-white/55">Choose a ship, then tap its starting square. Tap again to reposition it.</p><div className="max-w-md"><Board label="Your fleet" fleet={fleet} interactive={!busy} onCell={place}/></div><button className={`${button} text-violet-300`} disabled={busy||Object.keys(fleet).length!==5} onClick={()=>act('ready',{fleet})}>Ready · Lock my ships</button></div>:<div className="grid gap-6 md:grid-cols-2"><Board label="Your fleet" fleet={game.fleets?.[currentUser.id]||{}} shots={game.shots?.[opponent?.id]||{}}/><div><Board label="Their waters" shots={game.shots?.[currentUser.id]||{}} interactive={myTurn&&!busy} selected={target&&square(target.row,target.col)} onCell={(row,col)=>setTarget({row,col})}/>{myTurn&&<button className={`${button} mt-4 text-violet-300`} disabled={!target||busy} onClick={()=>act('fire',target)}>Fire{target?` at ${coordinate(target.row,target.col)}`:''}</button>}</div></div>}
      {confirmFinish?<div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>act('finish')}>End this game</button><button className={button} onClick={()=>setConfirmFinish(false)}>Keep playing</button></div>:<button className="battle-end inline-flex items-center gap-2 rounded-xl px-4 py-3 text-sm" onClick={()=>setConfirmFinish(true)}><Flag className="h-4 w-4"/>End game</button>}
    </>}
    {featured&&finished&&player&&<div className="grid gap-6 md:grid-cols-2"><Board label="Your fleet" fleet={game.fleets?.[currentUser.id]||{}} shots={game.shots?.[opponent?.id]||{}}/><Board label="Their fleet" fleet={game.fleets?.[opponent?.id]||{}} shots={game.shots?.[currentUser.id]||{}}/></div>}
    {featured&&game&&<div className="battle-log rounded-2xl border border-white/10 p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-medium">Battle Log</h3><span className="text-[10px] uppercase tracking-widest text-white/40">{finished?'Finished':'Saved'}</span></div>{!battleLog.length?<p className="text-sm text-white/40">Quiet waters. Who’s making the first move?</p>:<ol className="max-h-48 overflow-y-auto space-y-2">{battleLog.map(shot=>{const [r,c]=shot.cell.split('_').map(Number);return <li key={`${shot.userId}:${shot.cell}`} className="flex items-center justify-between gap-3 text-xs"><span className="font-mono text-white/65">{shot.name} fired at {coordinate(r,c)}: <span className={shot.hit?'text-orange-400':'text-purple-300'}>{shot.sunk?`${shot.sunk} sunk!`:shot.hit?'Direct hit!':'Miss.'}{shot.hit&&<Flame className="ml-1 inline h-3 w-3"/>}</span></span><time className="shrink-0 text-[10px] text-white/35" dateTime={new Date(shot.at).toISOString()}>{new Date(shot.at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'})}</time></li>;})}</ol>}</div>}
  </>;
  return featured?<section className="battle-game lounge-battle-panel rounded-2xl border p-5 sm:p-6 space-y-5"><header className="flex flex-wrap items-center justify-between gap-4"><button className={`${button} inline-flex items-center gap-2 text-white/60`} onClick={onClose}><ArrowLeft className="h-3 w-3"/>Back to music</button><div className="text-center"><h2 className="battle-title text-3xl font-medium">Battleship</h2><p className="mt-1 text-[10px] uppercase tracking-widest text-white/45">Sink ships. Start trouble.</p></div><p className="battle-turn max-w-56 rounded-xl px-3 py-2 text-xs" role="status"><span aria-hidden="true">● </span>{status}</p></header>{content}</section>:<details className="rounded-2xl border border-white/10 p-4"><summary className="cursor-pointer font-semibold">Battleship</summary><div className="mt-3 space-y-3">{content}</div></details>;
}
