export const QUESTIONS_FOR_US = [
  "When do you feel most understood by me?",
  "What did love look like in your home growing up?",
  "What is something you wish people asked you about more often?",
  "When life gets difficult, what kind of support actually helps you?",
  "What small thing makes you feel especially loved?",
  "What part of yourself are you learning to be kinder to?",
  "What is a dream you have not said out loud very often?",
  "What does a peaceful life look like to you?",
  "What is something you want us to get better at together?",
  "Which experience changed the way you see yourself?",
  "What do you need when we disagree: space, reassurance, conversation, or something else?",
  "What is a memory of us that you return to when you miss me?",
  "What is something you are proud of that others might not notice?",
  "What does trust feel like to you in everyday life?",
  "What is a fear you would like me to understand better?",
  "What have you changed your mind about in the last few years?",
  "Which version of your younger self would you most like to comfort?",
  "What is something you hope we never stop doing?",
  "When do you feel most like yourself?",
  "What boundary helps you feel safe and respected?",
  "What is something you are still figuring out about your future?",
  "What would you like more of in our ordinary days together?",
  "What is one lesson you learned the hard way?",
  "What does commitment mean to you beyond the big promises?",
  "What would you like to ask me but have not found the right moment for?",
  "If our relationship had a ridiculous movie title, what would it be?",
  "What snack best represents your personality, and why?",
  "If we could teleport somewhere for dinner tonight, where would we go?",
  "Which fictional world would you want us to spend a weekend in?",
  "What song would play every time you entered a room?",
  "What completely useless skill would you love to master?",
  "If we opened a tiny shop together, what would we sell?",
  "What would your very dramatic autobiography be called?",
  "Which animal would be the worst roommate for us?",
  "What is your most defensible unpopular food opinion?",
  "If we had to compete on a TV show together, which one would we choose?",
  "What is a tiny inconvenience that you react to like a major betrayal?",
  "If you could keep only three apps on your phone, which ones would survive?",
  "What is the strangest thing you believed as a child?",
  "What would we do with a completely free day and no responsibilities?",
  "Which outfit of mine would you steal if it fit perfectly?",
  "If our secret room had a mascot, what would it be?",
  "What is a silly hill you are absolutely willing to die on?",
  "What would you name a boat, even if you never plan to own one?",
  "Which everyday activity deserves an Olympic event?",
  "If we swapped lives for a day, what would you do first?",
  "What is your ideal rainy-day combination of food, music, and activity?",
  "Which smell instantly brings back a particular memory?",
  "If you could send me one object that appeared instantly beside me, what would it be?",
  "What is the most oddly specific thing that makes you happy?",
  "What’s the most sensitive spot on your body that instantly turns you on when touched?",
  "Do you prefer slow, delicate kisses on your neck or heavy, breathless ones?",
  "What’s your biggest forbidden or unfiltered fantasy when it comes to women?",
  "If my hands were under your shirt right now, where would you want them to go first?",
  "What’s a physical habit of yours in bed that always drives a woman wild?",
  "Do you like being pinned down, or do you prefer pinning her down and taking full control?",
  "What’s the loudest or most intense reaction you’ve ever had during an intimate moment?",
  "Have you ever been kissed so deeply by a woman that you completely lost track of time?",
  "What’s something incredibly naughty you’ve always wanted a woman to do to you?",
  "If we locked the door and took off all our clothes right now, what’s the first thing you’d do to me?",
  "What’s the first thing you notice about another woman when you’re attracted to her?",
  "Soft and slow touch, or deep and intense tension—which one gets to you faster?",
  "What’s a subtle way a woman can touch you that instantly sends a shiver down your spine?",
  "Do you prefer being gently held against something, or being the one pulling her close?",
  "What’s your favorite physical feature on another woman’s body to trace with your fingers?",
  "Have you ever had a crush on a woman and kept it a total secret—what made her so intoxicating?",
  "If I put my hand on your waist right now, what would your immediate reaction be?",
  "What’s the hottest thing a woman can whisper in your ear?",
  "Do you like a prolonged eye-contact build-up before a kiss, or do you prefer just leaning in unprompted?",
  "If we were sitting alone together in the dark right now, how long do you think we’d last before someone made a move?",
  "What’s a fantasy or scenario you’ve always wanted to try?",
  "Where is the riskiest place you’ve ever made out or hooked up?",
  "What’s a specific outfit, look, or style that you find insanely attractive?",
  "Morning passion or late-night chemistry?",
  "What’s a word or phrase that instantly turns you on?",
  "What’s your favorite spot on your body to be touched or kissed?",
  "Do you prefer taking control or letting the other person take the lead?",
  "What’s the most intense chemistry you’ve ever felt with someone right off the bat?",
  "What’s your secret wildcard move when you really want to seduce someone?",
  "If we were alone in a room right now with no distractions, what would you want to do first?",
  "If you could know the exact date and time of your death, would you want to know?",
  "Do you believe everything happens for a reason, or is life mostly random?",
  "If you could relive one year of your life without changing anything, which year would it be?",
  "What do you think happens after we die?",
  "If time travel were possible, would you go to the past or the future?",
  "Do you think humans are inherently good, bad, or neutral?",
  "If you could ask an omniscient being one question about your life, what would it be?",
  "What’s a mystery about the universe or history you wish you had the answer to?",
  "Do you think true selflessness exists, or is every act somewhat selfish?",
  "If you could freeze time for 24 hours and do anything without consequences, what would you do?",
  "Would you rather live a short, incredibly exciting life or a long, peaceful one?",
  "Do you think free will exists, or are we guided by environment and genetics?",
  "What legacy do you want to leave behind when you’re gone?",
  "If you could talk to your 80-year-old self, what would you ask them?",
  "Is it better to love and lose, or never to have loved at all?",
  "What’s a memory from your childhood that shaped who you are today?",
  "What’s something you’re currently working through or trying to improve about yourself?",
  "What is your biggest fear when it comes to relationships?",
  "What’s a lesson you had to learn the hard way?",
  "Who in your life knows you better than anyone else?",
  "What’s a dream or goal you’ve never told many people about?",
  "What makes you feel truly understood by someone?",
  "What’s the hardest decision you’ve ever had to make?",
  "What does \"home\" mean to you?",
  "What’s a belief you used to hold strongly that you’ve completely changed your mind on?",
  "What are three things you value most in a friendship?",
  "How do you handle conflict or bad days?",
  "What is something you’re proud of that you don’t get to brag about enough?",
  "What’s a boundary that is non-negotiable for you in life?",
  "What’s the best piece of wisdom you’ve ever received?",
  "What makes you feel most insecure, and how do you handle it?",
  "What’s a side of you that most people don’t see right away?",
  "When was the last time you cried, and why?",
  "What does success mean to you at this stage of your life?",
  "What’s a habit or trait you admire most in others?",
  "What’s something you feel you’re still searching for in life?",
  "How do you like to be comforted when you’re stressed or sad?",
  "What’s a risk you took that completely changed your life?",
  "What is your relationship like with your family?",
  "What’s a truth about yourself that took you a long time to accept?",
  "What was your very first impression of me?",
  "What’s your biggest turn-on that isn’t physical?",
  "What’s the most romantic thing someone has ever done for you?",
  "Do you prefer subtle flirting or bold, direct moves?",
  "What’s your favorite physical feature on yourself?",
  "What’s a compliment you received that you still think about?",
  "What’s your idea of a perfect first date?",
  "How do you usually show someone you like them without saying it?",
  "Do you believe in love at first sight, or should I walk past again?",
  "What’s something subtle someone can do that instantly makes them attractive?",
  "What’s the best date night outfit in your wardrobe?",
  "Are you a hugger, a hand-holder, or a kiss-on-the-cheek person?",
  "What’s a romantic cliché you actually secretly love?",
  "What’s the quickest way to make you blush?",
  "If we were trapped in an elevator together for three hours, what would we do?",
  "What’s your absolute favorite way to be spoiled?",
  "Do you fall in love fast or slow?",
  "What’s a song that always puts you in a romantic mood?",
  "If you could take me anywhere in the world right now, where are we going?",
  "What’s your favorite habit or trait in a potential partner?",
  "What’s the best kiss you’ve ever had—what made it so good?",
  "What’s something you find irresistibly attractive about me?",
  "What’s your stance on PDA (public displays of affection)?",
  "If you had to write a dating profile headline for me, what would it say?",
  "What’s your love language: Words, Acts, Gifts, Time, or Touch?",
];

export function pickQuestion(previousIndex, random = Math.random) {
  const options = QUESTIONS_FOR_US.map((_, index) => index).filter(index => index !== previousIndex);
  return options[Math.min(options.length - 1, Math.floor(random() * options.length))];
}

export function updateQuestionGame(game, action) {
  const current = game?.current;
  if (action.type === 'new') {
    if (current?.id !== action.expectedId) return;
    const count = Object.keys(current?.answers || {}).length;
    if (count === 1) return;
    if (!Number.isInteger(action.questionIndex) || !QUESTIONS_FOR_US[action.questionIndex]) return;
    if (current && current.questionIndex === action.questionIndex) return;
    const history = { ...game?.history };
    if (count === 2) history[current.id] = current;
    return { ...game, history, current: { id: action.id, questionIndex: action.questionIndex, createdAt: action.now } };
  }
  if (action.type === 'answer') {
    const blocks = action.blocks;
    if (!current || current.id !== action.expectedId || !action.user?.id || (!action.text?.trim() && !blocks?.length)) return;
    const answers = current.answers || {};
    if (answers[action.user.id] || Object.keys(answers).length >= 2) return;
    return { ...game, current: { ...current, answers: { ...answers, [action.user.id]: { name: action.user.name || 'Someone', text: action.text?.trim() || '', ...(blocks?.length ? { blocks } : {}), answeredAt: action.now } } } };
  }
}
