const phrases = (theme, category, text) => text.map((answer, index) => ({ id:`${theme}-${category}-${index}`, answer, category }));

export const WHEEL_THEMES = [
  { id:'spicy', name:'Spicy', description:'Flirting, tension, and a little trouble.', phrases:[
    ...phrases('spicy','Person / Directive',[
      'LOOK ME IN THE EYES','COME A LITTLE CLOSER','DO NOT MAKE ME WAIT','TELL ME WHAT YOU WANT','PUT YOUR HANDS ON ME','TAKE OFF YOUR SHIRT',
    ]),
    ...phrases('spicy','What Are You Doing?',[
      'DRIVING ME WILD','TASTING MY LIPS','MAKING ME BLUSH','PLAYING HARD TO GET','WHISPERING IN MY EAR','BEING A BAD INFLUENCE',
    ]),
    ...phrases('spicy','Phrase',[
      'YOU ARE DISTRACTING ME','I WANT YOU ALL TO MYSELF','YOU ARE IN TROUBLE TONIGHT','MY HANDS ARE ALL YOURS','YOU CANNOT RESIST ME','WE SHOULD TAKE THIS UPSTAIRS','YOU MAKE MY HEART RACE','I CANNOT STOP THINKING ABOUT YOU',
    ]),
  ] },
  { id:'music', name:'Music · The ’90s', description:'Guess the title of a ’90s song.', phrases:[
    ['SMELLS LIKE TEEN SPIRIT','Nirvana',1991],['NO SCRUBS','TLC',1999],['WATERFALLS','TLC',1995],['WANNABE','Spice Girls',1996],['I WANT IT THAT WAY','Backstreet Boys',1999],['...BABY ONE MORE TIME','Britney Spears',1998],['BLACK HOLE SUN','Soundgarden',1994],['CREEP','Radiohead',1992],['UNDER THE BRIDGE','Red Hot Chili Peppers',1991],['DON\'T SPEAK','No Doubt',1995],['ZOMBIE','The Cranberries',1994],['BITTER SWEET SYMPHONY','The Verve',1997],['KISS FROM A ROSE','Seal',1994],['TORN','Natalie Imbruglia',1997],['LOSING MY RELIGION','R.E.M.',1991],['ENJOY THE SILENCE','Depeche Mode',1990],['VOGUE','Madonna',1990],['BELIEVE','Cher',1998],['GANGSTA\'S PARADISE','Coolio',1995],['IRIS','Goo Goo Dolls',1998],
  ].map(([answer,artist,year], index) => ({ id:`music-${index}`,answer,category:'Song title',artist,year })) },
  { id:'date-night', name:'Date Night', description:'Plans worth putting your phone away for.', phrases:phrases('date-night','Date idea',[
    'DINNER UNDER THE STARS','A PICNIC BY THE WATER','DANCING IN THE KITCHEN','A SUNSET WALK TOGETHER','ONE MORE EPISODE WITH YOU','BREAKFAST IN BED','A BLANKET FORT FOR TWO','TAKING THE LONG WAY HOME','A CANDLELIT DINNER','GETTING LOST IN A BOOKSHOP','A NIGHT AT THE MOVIES','COOKING SOMETHING NEW TOGETHER','A SLOW DANCE IN THE LIVING ROOM','WATCHING THE RAIN FROM THE WINDOW','A MIDNIGHT ICE CREAM RUN','TWO TICKETS TO ANYWHERE','SINGING OUR FAVORITE SONGS','A DAY WITH NO PLANS','STAYING IN AND ORDERING TAKEOUT','A LITTLE SURPRISE JUST FOR YOU',
  ]) },
  { id:'sweet-talk', name:'Sweet Talk', description:'Little things you might leave on our wall.', phrases:phrases('sweet-talk','A little love note',[
    'YOU FEEL LIKE HOME','MY FAVORITE PLACE IS NEXT TO YOU','I SAVED YOU THE LAST BITE','YOU MAKE ORDINARY DAYS BETTER','I LIKE WHO I AM WITH YOU','THINKING OF YOU AGAIN','THERE IS ALWAYS ROOM FOR YOU','I AM GLAD WE FOUND EACH OTHER','YOUR LAUGH IS MY FAVORITE SOUND','LET ME MAKE YOU SOME TEA','I AM ON YOUR SIDE','YOU MAKE THE DISTANCE FEEL SMALLER','A LITTLE NOTE TO MAKE YOU SMILE','I WISH YOU WERE HERE','THIS SONG MADE ME THINK OF YOU','YOU ARE MY FAVORITE HELLO','I WILL SAVE YOU A SEAT','I LOVE OUR LITTLE ROUTINES','YOU CAN ALWAYS TALK TO ME','JUST ONE MORE HUG',
  ]) },
  { id:'food', name:'Food & Cravings', description:'Snacks, cravings, and kitchen adventures.', phrases:phrases('food','Food & drink',[
    'PIZZA WITH EXTRA CHEESE','CHOCOLATE COVERED STRAWBERRIES','FRESHLY BAKED CINNAMON ROLLS','FRENCH FRIES FOR THE TABLE','A GIANT BOWL OF POPCORN','PANCAKES WITH MAPLE SYRUP','HOT CHOCOLATE ON A COLD NIGHT','PASTA WITH HOMEMADE SAUCE','ICE CREAM STRAIGHT FROM THE TUB','COFFEE BEFORE CONVERSATION','THE LAST SLICE OF CAKE','SUSHI AND A MOVIE','TACOS AFTER MIDNIGHT','A PERFECTLY TOASTED SANDWICH','STILL WARM CHOCOLATE CHIP COOKIES','BREAKFAST FOR DINNER','ONE MORE SPOONFUL OF DESSERT','A VERY SERIOUS CHEESE BOARD','SPICY NOODLES AND COLD DRINKS','THE SECRET INGREDIENT IS BUTTER',
  ]) },
  { id:'adventures', name:'Little Adventures', description:'Places to go and memories to make.', phrases:phrases('adventures','Adventure',[
    'A ROAD TRIP WITH NO DESTINATION','WATCHING THE NORTHERN LIGHTS','GETTING LOST IN A NEW CITY','A CABIN IN THE MOUNTAINS','SWIMMING UNDER THE STARS','A PASSPORT FULL OF MEMORIES','CATCHING THE FIRST TRAIN OUT','A SECRET BEACH AT SUNSET','CAMPING BESIDE A QUIET LAKE','A WEEKEND WITHOUT OUR PHONES','CHASING THE PERFECT SUNSET','FINDING A HIDDEN WATERFALL','A LITTLE HOUSE BY THE SEA','TAKING PHOTOS IN THE RAIN','A WINDOW SEAT ON THE PLANE','EXPLORING A TINY COASTAL TOWN','A LONG WALK THROUGH THE FOREST','GETTING UP EARLY FOR THE VIEW','MAKING A PLAYLIST FOR THE ROAD','BRINGING HOME TOO MANY SOUVENIRS',
  ]) },
  { id:'chaos', name:'Everyday Chaos', description:'The wonderfully ridiculous parts of life.', phrases:phrases('chaos','Everyday life',[
    'WHERE DID I PUT MY KEYS','JUST FIVE MORE MINUTES','THE LAUNDRY CHAIR IS FULL','ACCIDENTALLY TAKING A THREE HOUR NAP','FORGETTING WHY I ENTERED THE ROOM','TALKING TO THE CAT AGAIN','THE PHONE WAS IN MY HAND','OPENING THE FRIDGE FOR NO REASON','MY BRAIN HAS TOO MANY TABS OPEN','BUYING ANOTHER PLANT','THE DISHES CAN WAIT UNTIL TOMORROW','WATCHING THE SAME MOVIE AGAIN','SENDING YOU ANOTHER SILLY MEME','OVERTHINKING A TWO WORD MESSAGE','ONE SOCK HAS LEFT THE CHAT','THE WIFI PICKED THE WORST MOMENT','PRETENDING THE ALARM NEVER RANG','DROPPING MY PHONE ON MY FACE','MAKING A TO DO LIST INSTEAD OF DOING IT','I CAME HERE FOR ONE THING',
  ]) },
];

export const wheelTheme = id => WHEEL_THEMES.find(theme => theme.id === id);
export const wheelPuzzle = game => wheelTheme(game?.themeId)?.phrases.find(phrase => phrase.id === game?.puzzleId);
